// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  BLUESKY_USERNAME: string;
  BLUESKY_PASSWORD: string;
  BLUESKY_FUN_KV: KVNamespace;
}
